lifelog:
  image: emag/lifelog:1.0.0
  environment:
    ENVIRONMENT_PRODUCTION: "true"
  links:
    - lifelog-db:db
    - lifelog-keycloak:keycloak
  ports:
    - 8080:8080
lifelog-db:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: lifelog
    POSTGRES_PASSWORD: lifelog
  volumes:
    - /tmp/lifelog/pgdata/data:/var/lib/postgresql/data
  ports:
    - 5432:5432
lifelog-keycloak:
  image: emag/keycloak:1.0.0
  ports:
    - 8180:8080